apiVersion: v1
kind: Service
metadata:
  name: alpinex-service
  namespace: default
spec:
  selector:
    app: alpinex
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090
---      
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpinex-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpinex
  template:
    metadata:
      labels:
        app: alpinex
    spec:
      containers:
      - name: alpinex-container
        image: droritzz/alpinex:1.13
        ports:
        - containerPort: 8090
